theme = "monokai"

[editor]
mouse = false
middle-click-paste = false
shell = ["bash", "-c"]
line-number = "relative"
completion-timeout = 5
completion-trigger-len = 1
completion-replace = true
true-color = true
popup-border = "all"
soft-wrap.enable = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left = [ "mode", "spacer", "version-control", "spacer", "spinner" ]
center = [ "file-modification-indicator", "file-name" ]
right = [ "diagnostics", "read-only-indicator", "position", "file-encoding", "file-line-ending" ]

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 15000

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
